# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='stock_price',
        ),
        migrations.AddField(
            model_name='stock',
            name='buy_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='current_price',
            field=models.FloatField(default=0),
        ),
    ]
