# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0002_auto_20170827_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_fund',
            field=models.FloatField(default=500000.0),
        ),
    ]
