# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0003_customuser_total_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='buy_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
